export default {
  primary: '#5B9FFF',
  primaryLight: '#8BBEFF',
  primaryDark: '#3A7BD5',
  accent: '#5B9FFF',
  background: '#F0F4FF',
  surface: '#FFFFFF',
  text: '#1A1A2E',
  textSecondary: '#6B7FA8',
  border: '#D6E0F0',
  error: '#FF6B6B',
  success: '#4ECDC4',
  warning: '#FFD93D',
  info: '#5B9FFF',
  darkBackground: '#1A1A2E',
  darkSurface: '#2A2A4E',
  darkText: '#E8EEFF',
  darkTextSecondary: '#8899CC',
  darkBorder: '#3A3A5E',
}
